### ISSUE TITLE
undefined local variable or method `cache_key_for_taxons'

### ISSUE THREAD

**Issue by harinsa** [AlchemyCMS/alchemy-solidus#1]
When visit `index` page. Was able to solve by adding 
`Alchemy::BaseHelper.send :include, Spree::StoreHelper` 
to `initializers/alchemy.rb`

**Comment by tvdeyen** [comment]
Ok. Then we need to update the README. Could you send a pull request? That would be great. Thanks

**Comment by harinsa** [comment]
Pull request created.
