### ISSUE TITLE
initializer - development - include helpers

### ISSUE THREAD

**Issue by oniram88** [AlchemyCMS/alchemy-solidus#13]
I have question, that I'm nostre how it can be implemented the solution.
we include the `require 'alchemy/solidus/alchemy_in_solidus'` in our initializer .

But when we make a change to application_controller in the app, all alchemy helpers are lost from our solidus base controller.
Is there a way to attach a config.to_prepare on the application to load this initializers programmaticaly? So I should't restart every time the application?

I hope that my question is clearly, excuse me for my poor english.

**Comment by tvdeyen** [comment]
Yes in your initializer you can use `config.to_prepare` and then use `require_dependency` from rails
