### ISSUE TITLE
Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded

### ISSUE THREAD

**Issue by joeczucha** [AlchemyCMS/alchemy-solidus#22]
I'm trying to use alchemy-solidus with postgresql.

I've set up the project using `--database=postgresql` and can create the databases, run the server, etc.

But when I add the gem (master, from github) to my Gemfile, run `bundle install` and then run `bundle exec rails s` I get the following:

    => Booting Puma
    => Rails 5.1.5 application starting in development
    => Run `rails server -h` for more startup options
    Exiting
    bundler: failed to load command: rails (/Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/rails)
    Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:188:in `rescue in spec'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:185:in `spec'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:880:in `establish_connection'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:58:in `establish_connection'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/railtie.rb:124:in `block (2 levels) in <class:Railtie>'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:41:in `block in on_load'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:40:in `each'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:40:in `on_load'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/railtie.rb:120:in `block in <class:Railtie>'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `each'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `call'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/initializable.rb:58:in `run_initializers'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/application.rb:353:in `initialize!'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/alchemy-solidus-0906127071ca/spec/dummy/config/environment.rb:5:in `<top (required)>'
    config.ru:3:in `require_relative'
    config.ru:3:in `block in <main>'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
    config.ru:in `new'
    config.ru:in `<main>'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:24:in `app'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:42:in `start'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:135:in `block in perform'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/engine/commands.rb:7:in `require'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.5/lib/rails/engine/commands.rb:7:in `<top (required)>'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/alchemy-solidus-0906127071ca/bin/rails:14:in `require'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/alchemy-solidus-0906127071ca/bin/rails:14:in `<top (required)>'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/rails:23:in `load'
    /Users/joe/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/rails:23:in `<top (required)>'

Possiblly something to do with `alchemy-solidus/spec/dummy/config/database.yml`? That's the only place I can find mention of any sqllite stuff...

Thanks in advance

**Comment by christophebeling** [comment]
+ 1

**Comment by tvdeyen** [comment]
Ups. We included development files into the final gem build. Fixed by #26
