### ISSUE TITLE
master_branch issue not detecting initialiser in Rails 5.

### ISSUE THREAD

**Issue by nxtbz** [AlchemyCMS/alchemy-solidus#23]
Issue: 

Installing alchemy_solidus:master_branch on Rails 5.
Stated you want to use the provided Spree::User, it doesn't recognizing the initaliser: 

```
config/initializers/alchemy.rb
Alchemy.user_class_name = 'Spree::User'
Alchemy.current_user_method = :current_spree_user 
```

Error: 
```
 AlchemyCMS cannot find any user class!
        Please add a user class and tell Alchemy about it or, if you don't want
        to create your own class, add the `alchemy-devise` gem to your Gemfile.
        gem 'alchemy-devise', '~> 2.1.0'
```

**Comment by tvdeyen** [comment]
Do you have `solidus_auth_devise` installed?

**Comment by nxtbz** [comment]
Yes.

**Comment by tvdeyen** [comment]
@nxtbz I just released a new version 2.2.0 with lots of fixes. Could you please update and see if this fixes your issues (that I can't reproduce)?

**Comment by nxtbz** [comment]
@tvdeyen thank you for all your work and effort. The update seems to fix the issue. Besides that I can confirm it also works with `solidus_multi_domain`.

**Comment by tvdeyen** [comment]
🎉
