### ISSUE TITLE
Create _essence_spree_product_view and _essence_spree_taxon_view when running installer

### ISSUE THREAD

**Issue by rickythefox** [AlchemyCMS/alchemy-solidus#36]
Shouldn't the installer create 
`app/views/alchemy/essences/_essence_spree_product_view.html.erb` and 
`app/views/alchemy/essences/_essence_spree_taxon_view.html.erb` 
and perhaps also add some dafaults (like `<%= content.ingredient.name %>`) to them? 

As it is, nothing is displayed when rendering the generated page, which is a bit confusing.

**Comment by tvdeyen** [comment]
Those files live in this gem and will be picked up by Rails Template lookup if no auch file exists in the host app. 

This said, are you sure you have a Taxon or product assigned in the backend?

**Comment by rickythefox** [comment]
IMO the installer should copy the files to the user application. `_essence_spree_product_view` is empty by default, so when you create an Alchemy page with a Solidus product, nothing is shown. 

You have to dig in the gem code to understand that you have to create `app/views/alchemy/essences/_essence_spree_product_view.html.erb` and use `content.ingredient` to get the Solidus product object. That is not in the docs what I've seen.

**Comment by tvdeyen** [comment]
Ok, know I see the confusion. Sorry.

I usually have the product rendering logic in my element that uses the `EssenceSpreeProduct`.

```erb
# app/views/alchemy/product_teaser.html.erb
<%= element_view_for element do |el| %>
  <% product = el.ingredient(:product) %>
  Price: <%= product.display_price %>
  ...
<% end %>
```

That way I can have multiple representations for the same product. The same is true for taxons.

```erb
# app/views/alchemy/taxon_teaser.html.erb
<%= element_view_for element do |el| %>
  <% taxon = el.ingredient(:taxon) %>
  Products count: <%= taxon.products.count %>
  ...
<% end %>
```

There is no advantage having this logic inside your essence product partials. That's why they are empty. Sorry, if that is not very obvious from the Readme.

**Comment by rickythefox** [comment]
Got it, thanks. Might be a useful snippet to add to the readme. :)

**Comment by tvdeyen** [comment]
@rickythefox yes, you are absolutely right. Thanks for reporting. Any chance you have time to provide a PR with that change? Maybe you have other things to add to the README as well that would help other newcomers?

**Comment by rickythefox** [comment]
Of course, will submit a PR next week.

**Comment by tvdeyen** [comment]
Awesome. Thank you!

**Comment by tvdeyen** [comment]
@rickythefox updated the README in #46 and included the element examples

**Comment by rickythefox** [comment]
Thank you! Completely forgot that I promised a PR, sorry about that!

**Comment by tvdeyen** [comment]
That’s fine. We all have other things to do :)

Is the example ok or can it be improved?

**Comment by rickythefox** [comment]
@tvdeyen I think the examples are great! Thanks for taking the time to write them.
