### ISSUE TITLE
Javascript Pack Tag Missing In Edit

### ISSUE THREAD

**Issue by gareth326771** [AlchemyCMS/alchemy-solidus#64]
Following error in http://localhost:3000/pages/admin/pages/3/edit:

NoMethodError in Alchemy::Admin::Pages#show
Showing /Users/garethphillips/code/gareth326771/PODD/app/views/layouts/application.html.erb where line #9 raised:

undefined method `javascript_pack_tag' for #<#<Class:0x00007fcb68cb8d20>:0x00007fcb68626480>
Did you mean?  javascript_path
               javascript_tag

---

To reproduce:

Install following instructions on gems below.
Routing alchemy @ '/pages'

---

Expected behaviour:
To be able to edit pages?

---

Gems:
gem 'solidus'
gem 'solidus_auth_devise'
gem 'alchemy-solidus', '~> 2.4.0'
gem 'cancancan', '~> 2.1'
gem 'alchemy_cms'

**Comment by tvdeyen** [comment]
I assume you are using latest Alchemy master. Have you ran the install generator? It should have installed webpacker for you. You can do this manually. Just run 

```
bin/rails webpacker:install
```

**Comment by gareth326771** [comment]
Yes I ran the install generator. That cmd produces this error `Don't know how to build task 'webpacker:install' (See the list of available tasks with `rails --tasks`)`

**Comment by tvdeyen** [comment]
Can you try to 

```
bundle add webpacker
```

and try again?

**Comment by tvdeyen** [comment]
I assume this is not an issue anymore? If this is still the case please reopen.
