### ISSUE TITLE
Rails 6 support?

### ISSUE THREAD

**Issue by vdanciu** [AlchemyCMS/alchemy-solidus#70]
**Is your feature request related to a problem? Please describe.**
I am upgrading solidus to Rails 6 and I am getting the `"Initialization autoloaded the constants"` deprecation warning.

Is there a plan to fix this or should I be doing something to fix this (if I remove this gem I don't get the warning anymore).

Here is the complete message:
`DEPRECATION WARNING: Initialization autoloaded the constants Spree::SocialConfiguration, Spree::RansackableAttributes, Spree::Base, Spree::Calculator, Spree::Calculator::RelatedProductDiscount, SolidusPayuGateway::Configuration, Spree::Admin, ApplicationHelper, Spree::BaseHelper, BaseHelper, Spree::OrdersHelper, OrdersHelper, Spree::ProductsHelper, ProductsHelper, StaticHelper, DeviseHelper, Spree::SoftDeletable, Spree::Product::Scopes, Spree::Product, Spree::TaxonFiltersHelper, Spree::Admin::AdjustmentsHelper, Spree::Admin::BaseHelper, Spree::Admin::CustomerReturnsHelper, Spree::Admin::NavigationHelper, Spree::Admin::OrdersHelper, Spree::Admin::PaymentsHelper, Spree::Admin::ProductsHelper, Spree::Admin::PromotionsHelper, Spree::Admin::ReimbursementTypeHelper, Spree::Admin::StockLocationsHelper, Spree::Admin::StockMovementsHelper, Spree::Payment::Processing, Spree::Payment, Spree::Refund, Spree::Admin::StoreCreditEventsHelper, Spree::PromotionRulesHelper, FontAwesome::Rails::IconHelper, ApplicationController, Spree::BaseController, Spree::Admin::BaseController, Spree::Order::Checkout, Spree::Order::Payments, Spree::DisplayMoney, Spree::Order, Spree::Admin::OrdersController, Spree::Admin::ResourceController, Spree::Admin::ProductsController, Spree::Admin::PromotionsController, Spree::Admin::StockItemsController, Spree::Admin::UsersController, ActionText::ContentHelper, ActionText::TagHelper, Spree::UserApiAuthentication, Spree::UserReporting, Spree::UserAddressBook, Spree::UserPaymentSource, Spree::UserMethods, Spree::User, Spree::PaymentMethod, and Spree::PaymentMethod::PayuRo`

**Comment by tvdeyen** [comment]
Rails 6 is supported by Solidus, Alchemy and this Gem. What you see is a deprecation warning about something that will change in later versions of Rails.

You can help us by sending a PR that changes the Code in the three Gems Solidus, Alchemy and this gem so that it will not break in future Rails versions.

Thanks for reporting.
