### ISSUE TITLE
Allow alchemy_cms (~> 6.0)

### ISSUE THREAD

**Issue by v-ruiz** [AlchemyCMS/alchemy-solidus#84]
**Is your feature request related to a problem? Please describe.**
I would like to upgrade alchemy_cms to version 6.0

**Describe the solution you'd like**
A new stable release with the upgraded dependencies

**Describe alternatives you've considered**
A custom fork and change dependencies.

**Additional context**
Thx for all the work you already done ✅

**Comment by tvdeyen** [comment]
We will release a stable version soon.

Meanwhile you can just point to the `main` branch

```rb
# Gemfile
gem "alchemy-solidus", github: "AlchemyCMS/alchemy-solidus", branch: "main"
```

**Comment by tvdeyen** [comment]
https://github.com/AlchemyCMS/alchemy-solidus/releases/tag/v4.0.0
